const img = (id) => `https://images.unsplash.com/${id}?w=400&q=80`;

export const CATEGORIES = ["Semua", "Sayuran", "Bumbu", "Protein", "Sembako"];

export const PRODUCTS = [
  {
    id: "kentang",
    name: "Kentang Granola",
    category: "Sayuran",
    price: 14000,
    old_price: 16000,
    unit: "kg",
    stock: 200,
    origin: "Cikajang, Garut",
    img: img("photo-1518977676601-b53f82aba655"),
    desc: "Kentang granola lokal Cikajang, umbi utuh, padat dan tidak bertunas. Cocok untuk direbus, digoreng, atau dibuat sop.",
    nutrition: { kalori: 77, protein: 2.0, karbo: 17.5, lemak: 0.1 },
  },
  {
    id: "telur",
    name: "Telur Ayam Negeri",
    category: "Protein",
    price: 27000,
    old_price: 29000,
    unit: "kg",
    stock: 150,
    origin: "Tarogong, Garut",
    img: img("photo-1582722872445-44dc5f7e3c8f"),
    desc: "Telur ayam negeri segar, cangkang bersih, kuning telur pekat. Sumber protein utama menu harian MBG.",
    nutrition: { kalori: 143, protein: 12.6, karbo: 0.7, lemak: 9.5 },
  },
  {
    id: "cabai-merah",
    name: "Cabai Merah Keriting",
    category: "Bumbu",
    price: 32000,
    old_price: 38000,
    unit: "kg",
    stock: 60,
    origin: "Bayongbong, Garut",
    img: img("photo-1592137403099-624c888e3f4d"),
    desc: "Cabai merah keriting segar, warna merah merata, pedas sedang. Bumbu wajib untuk sambal dan tumisan.",
    nutrition: { kalori: 40, protein: 1.9, karbo: 8.8, lemak: 0.4 },
  },
  {
    id: "cabai-rawit",
    name: "Cabai Rawit Merah",
    category: "Bumbu",
    price: 38000,
    old_price: 42000,
    unit: "kg",
    stock: 45,
    origin: "Samarang, Garut",
    img: img("photo-1587131787055-e62b21a7752a"),
    desc: "Cabai rawit merah pilihan, pedasnya nendang. Segar dipetik, cocok untuk sambal bawang.",
    nutrition: { kalori: 40, protein: 2.4, karbo: 7.5, lemak: 0.6 },
  },
  {
    id: "bawang-merah",
    name: "Bawang Merah",
    category: "Bumbu",
    price: 30000,
    old_price: 34000,
    unit: "kg",
    stock: 120,
    origin: "Garut Kota",
    img: img("photo-1508747703725-719777637510"),
    desc: "Bawang merah lokal, umbi keras dan tidak busuk. Aroma kuat untuk menumis segala masakan.",
    nutrition: { kalori: 40, protein: 1.5, karbo: 9.3, lemak: 0.2 },
  },
  {
    id: "bawang-putih",
    name: "Bawang Putih Kating",
    category: "Bumbu",
    price: 28000,
    old_price: 32000,
    unit: "kg",
    stock: 100,
    origin: "Impor & Lokal",
    img: img("photo-1540151812223-b30b3fab58e6"),
    desc: "Bawang putih kating, siung besar dan kering. Bumbu dasar semua masakan Indonesia.",
    nutrition: { kalori: 149, protein: 6.4, karbo: 33.1, lemak: 0.5 },
  },
  {
    id: "beras",
    name: "Beras Premium Setra Ramos",
    category: "Sembako",
    price: 15500,
    old_price: 16500,
    unit: "kg",
    stock: 500,
    origin: "Cibatu, Garut",
    img: img("photo-1586201375761-83865001e31c"),
    desc: "Beras premium setra ramos, pulen, bersih tanpa batu. Bahan pokok nasi di setiap dapur MBG.",
    nutrition: { kalori: 360, protein: 6.6, karbo: 78.9, lemak: 0.6 },
  },
  {
    id: "minyak",
    name: "Minyak Goreng",
    category: "Sembako",
    price: 18000,
    old_price: 19000,
    unit: "liter",
    stock: 180,
    origin: "Garut Kota",
    img: img("photo-1474979266404-7eaacbcd87c5"),
    desc: "Minyak goreng kemasan, bening dan bebas kolesterol. Untuk menggoreng lauk pauk harian.",
    nutrition: { kalori: 884, protein: 0, karbo: 0, lemak: 100 },
  },
  {
    id: "gula",
    name: "Gula Pasir Putih",
    category: "Sembako",
    price: 17500,
    old_price: 18500,
    unit: "kg",
    stock: 90,
    origin: "Garut Kota",
    img: img("photo-1581795669223-09203b83bf61"),
    desc: "Gula pasir putih murni, halus dan kering. Untuk bumbu, minuman, dan kudapan.",
    nutrition: { kalori: 394, protein: 0, karbo: 100, lemak: 0 },
  },
  {
    id: "tepung",
    name: "Tepung Terigu",
    category: "Sembako",
    price: 12000,
    old_price: 13000,
    unit: "kg",
    stock: 110,
    origin: "Garut Kota",
    img: img("photo-1509440159596-0249088772ff"),
    desc: "Tepung terigu protein sedang, halus. Untuk roti, gorengan, dan aneka olahan tepung.",
    nutrition: { kalori: 365, protein: 10.3, karbo: 76.3, lemak: 1.2 },
  },
  {
    id: "tomat",
    name: "Tomat Merah",
    category: "Sayuran",
    price: 10000,
    old_price: 12000,
    unit: "kg",
    stock: 80,
    origin: "Leles, Garut",
    img: img("photo-1546094096-0df4bcaaa337"),
    desc: "Tomat merah segar, berair dan manis. Untuk sambal, sayur, dan pelengkap hidangan.",
    nutrition: { kalori: 18, protein: 0.9, karbo: 3.9, lemak: 0.2 },
  },
  {
    id: "wortel",
    name: "Wortel",
    category: "Sayuran",
    price: 12000,
    old_price: 14000,
    unit: "kg",
    stock: 75,
    origin: "Cisurupan, Garut",
    img: img("photo-1447175008436-054170c2e979"),
    desc: "Wortel segar, renyah, kaya vitamin A. Untuk sayur sop, capcay, dan jus.",
    nutrition: { kalori: 41, protein: 0.9, karbo: 9.6, lemak: 0.2 },
  },
  {
    id: "bayam",
    name: "Bayam Hijau",
    category: "Sayuran",
    price: 5000,
    old_price: 6000,
    unit: "ikat",
    stock: 70,
    origin: "Leles, Garut",
    img: img("photo-1576045057995-568f588f82fb"),
    desc: "Bayam hijau segar, daun muda dan bersih. Untuk sayur bening dan tumis bayam.",
    nutrition: { kalori: 23, protein: 2.9, karbo: 3.6, lemak: 0.4 },
  },
  {
    id: "kangkung",
    name: "Kangkung",
    category: "Sayuran",
    price: 4000,
    old_price: 5000,
    unit: "ikat",
    stock: 85,
    origin: "Bayongbong, Garut",
    img: img("photo-1563245372-f21724e3856d"),
    desc: "Kangkung segar, batang renyah. Untuk tumis kangkung dan plecing.",
    nutrition: { kalori: 19, protein: 3.0, karbo: 3.1, lemak: 0.3 },
  },
  {
    id: "tahu",
    name: "Tahu Putih",
    category: "Protein",
    price: 12000,
    old_price: 13000,
    unit: "kg",
    stock: 65,
    origin: "Tarogong, Garut",
    img: img("photo-1546069901-d5bfd2cbfb2c"),
    desc: "Tahu putih lembut, dibuat dari kedelai pilihan. Sumber protein nabati serbaguna.",
    nutrition: { kalori: 80, protein: 8.0, karbo: 1.9, lemak: 4.5 },
  },
  {
    id: "tempe",
    name: "Tempe Kedelai",
    category: "Protein",
    price: 11000,
    old_price: 12000,
    unit: "kg",
    stock: 70,
    origin: "Garut Kota",
    img: img("photo-1601050690597-df0568f70950"),
    desc: "Tempe kedelai segar, rapat dan tidak hancur. Kaya protein dan serat.",
    nutrition: { kalori: 193, protein: 20.8, karbo: 7.6, lemak: 10.9 },
  },
  {
    id: "ikan-nila",
    name: "Ikan Nila Segar",
    category: "Protein",
    price: 32000,
    old_price: 36000,
    unit: "kg",
    stock: 40,
    origin: "Sukaresmi, Garut",
    img: img("photo-1615141982883-c7ad0e69fd62"),
    desc: "Ikan nila segar hasil budidaya air tawar, daging putih gurih. Untuk digoreng atau dibakar.",
    nutrition: { kalori: 128, protein: 26, karbo: 0, lemak: 2.7 },
  },
  {
    id: "ayam",
    name: "Ayam Potong",
    category: "Protein",
    price: 35000,
    old_price: 38000,
    unit: "kg",
    stock: 55,
    origin: "RPH Garut",
    img: img("photo-1604503468506-a8da13d82791"),
    desc: "Ayam potong segar, dipotong bersih sesuai bagian. Fleksibel untuk semua olahan ayam.",
    nutrition: { kalori: 217, protein: 25, karbo: 0, lemak: 12 },
  },
  {
    id: "daging-sapi",
    name: "Daging Sapi Segar",
    category: "Protein",
    price: 135000,
    old_price: 140000,
    unit: "kg",
    stock: 25,
    origin: "RPH Garut",
    img: img("photo-1551024709-8f23befc6f87"),
    desc: "Daging sapi segar, merah cerah tanpa lemak berlebih. Untuk semur, rendang, dan tumisan.",
    nutrition: { kalori: 250, protein: 26, karbo: 0, lemak: 15 },
  },
  {
    id: "jagung",
    name: "Jagung Manis",
    category: "Sayuran",
    price: 8000,
    old_price: 9000,
    unit: "buah",
    stock: 100,
    origin: "Cikajang, Garut",
    img: img("photo-1551754655-cd27e38d2076"),
    desc: "Jagung manis pipil utuh, manis alami. Untuk sup jagung, bakwan, dan rebusan.",
    nutrition: { kalori: 96, protein: 3.4, karbo: 21, lemak: 1.5 },
  },
];

export function formatRp(n) {
  return "Rp " + (n || 0).toLocaleString("id-ID");
}
