// Seed data dummy untuk klon full-local.
// ensureSeed() dijalankan otomatis oleh adapter base44Client saat pertama kali
// dimuat. Data hanya di-seed sekali (versi dicek via localStorage key).

import { PRODUCTS } from "@/lib/marketplace";

const SEED_VERSION = "smb_seed_v5";

const now = () => new Date().toISOString();
const daysAgo = (n) => new Date(Date.now() - n * 86400000).toISOString();
const hoursAgo = (n) => new Date(Date.now() - n * 3600000).toISOString();

const uid = (p) => `${p}_${Math.random().toString(36).slice(2, 8)}`;

const WEEKLY_MENU = {
  week_label: "Menu Minggu Ini",
  menu_data: {
    Senin: {
      ingredients: [
        { nama: "Nasi Putih", jumlah: "100 g", gram_per_porsi: 100, kalori: 130, protein: 2.4, karbo: 28.2, lemak: 0.3 },
        { nama: "Ayam Goreng Tepung", jumlah: "80 g", gram_per_porsi: 80, kalori: 200, protein: 18, karbo: 8, lemak: 12 },
        { nama: "Tahu Goreng", jumlah: "50 g", gram_per_porsi: 50, kalori: 80, protein: 6, karbo: 2, lemak: 6 },
        { nama: "Sayur Bening Bayam", jumlah: "100 g", gram_per_porsi: 100, kalori: 30, protein: 3, karbo: 5, lemak: 0.5 },
        { nama: "Pisang", jumlah: "1 buah", gram_per_porsi: 100, kalori: 90, protein: 1, karbo: 23, lemak: 0.3 },
      ],
    },
    Selasa: {
      ingredients: [
        { nama: "Nasi Putih", jumlah: "100 g", gram_per_porsi: 100, kalori: 130, protein: 2.4, karbo: 28.2, lemak: 0.3 },
        { nama: "Semur Daging Sapi", jumlah: "80 g", gram_per_porsi: 80, kalori: 180, protein: 18, karbo: 5, lemak: 10 },
        { nama: "Tempe Bacem", jumlah: "50 g", gram_per_porsi: 50, kalori: 100, protein: 9, karbo: 8, lemak: 4 },
        { nama: "Tumis Buncis Wortel", jumlah: "100 g", gram_per_porsi: 100, kalori: 45, protein: 2, karbo: 8, lemak: 1 },
        { nama: "Jeruk", jumlah: "1 buah", gram_per_porsi: 100, kalori: 60, protein: 1.2, karbo: 15, lemak: 0.2 },
      ],
    },
    Rabu: {
      ingredients: [
        { nama: "Nasi Putih", jumlah: "100 g", gram_per_porsi: 100, kalori: 130, protein: 2.4, karbo: 28.2, lemak: 0.3 },
        { nama: "Ikan Fillet Asam Manis", jumlah: "100 g", gram_per_porsi: 100, kalori: 150, protein: 18, karbo: 10, lemak: 5 },
        { nama: "Perkedel Tahu", jumlah: "50 g", gram_per_porsi: 50, kalori: 70, protein: 5, karbo: 4, lemak: 4 },
        { nama: "Sayur Sop Bening", jumlah: "150 g", gram_per_porsi: 150, kalori: 40, protein: 2, karbo: 6, lemak: 1 },
        { nama: "Melon", jumlah: "150 g", gram_per_porsi: 150, kalori: 50, protein: 1, karbo: 12, lemak: 0.2 },
      ],
    },
    Kamis: {
      ingredients: [
        { nama: "Nasi Putih", jumlah: "100 g", gram_per_porsi: 100, kalori: 130, protein: 2.4, karbo: 28.2, lemak: 0.3 },
        { nama: "Ayam Teriyaki", jumlah: "80 g", gram_per_porsi: 80, kalori: 180, protein: 20, karbo: 8, lemak: 9 },
        { nama: "Tempe Goreng Crispy", jumlah: "50 g", gram_per_porsi: 50, kalori: 120, protein: 8, karbo: 9, lemak: 6 },
        { nama: "Tumis Sawi Hijau", jumlah: "100 g", gram_per_porsi: 100, kalori: 35, protein: 2.5, karbo: 5, lemak: 0.5 },
        { nama: "Apel", jumlah: "1 buah", gram_per_porsi: 100, kalori: 80, protein: 0.4, karbo: 21, lemak: 0.2 },
      ],
    },
    Jumat: {
      ingredients: [
        { nama: "Nasi Putih", jumlah: "100 g", gram_per_porsi: 100, kalori: 130, protein: 2.4, karbo: 28.2, lemak: 0.3 },
        { nama: "Telur Dadar / Balado", jumlah: "2 butir", gram_per_porsi: 100, kalori: 150, protein: 12, karbo: 2, lemak: 10 },
        { nama: "Tahu Isi Sayur", jumlah: "50 g", gram_per_porsi: 50, kalori: 60, protein: 4, karbo: 5, lemak: 3 },
        { nama: "Tumis Kacang Panjang", jumlah: "100 g", gram_per_porsi: 100, kalori: 40, protein: 2.5, karbo: 7, lemak: 0.5 },
        { nama: "Jeruk", jumlah: "1 buah", gram_per_porsi: 100, kalori: 60, protein: 1.2, karbo: 15, lemak: 0.2 },
      ],
    },
    Sabtu: {
      ingredients: [
        { nama: "Nasi Goreng / Nasi Putih", jumlah: "150 g", gram_per_porsi: 150, kalori: 220, protein: 5, karbo: 40, lemak: 5 },
        { nama: "Ayam Bakar", jumlah: "100 g", gram_per_porsi: 100, kalori: 200, protein: 22, karbo: 2, lemak: 12 },
        { nama: "Tempe Orek Kering", jumlah: "30 g", gram_per_porsi: 30, kalori: 80, protein: 6, karbo: 5, lemak: 4 },
        { nama: "Cah Kangkung / Capcay", jumlah: "100 g", gram_per_porsi: 100, kalori: 35, protein: 2, karbo: 5, lemak: 1 },
        { nama: "Semangka", jumlah: "200 g", gram_per_porsi: 200, kalori: 60, protein: 1, karbo: 15, lemak: 0.3 },
      ],
    },
    Minggu: { ingredients: [] },
  },
};

const COLLECTIONS = {
  users: [
    { id: "u_warga", email: "adhiramaharani@gmail.com", password: "SmartMBG2026!", full_name: "Adhira Maharani", role: "penerima", verified: true, created_date: now() },
    { id: "u_mitra", email: "mitra@demo.local", password: "demo1234", full_name: "Mitra SPPG Cikajang", role: "mitra", verified: true, created_date: now() },
    { id: "u_supplier", email: "supplier@demo.local", password: "demo1234", full_name: "CV Binar Kalasenja", role: "supplier", verified: true, created_date: now() },
    { id: "u_logistik", email: "logistik@demo.local", password: "demo1234", full_name: "Tim Logistik Pemkab Garut", role: "logistik", verified: true, created_date: now() },
    { id: "u_admin", email: "admin@demo.local", password: "demo1234", full_name: "Administrator", role: "admin", verified: true, created_date: now() },
  ],
  UserProfile: [
    { id: "p_warga", user_id: "u_warga", user_email: "adhiramaharani@gmail.com", full_name: "Adhira Maharani", role: "penerima", is_active: true, phone: "081234567890", address: "Jl. Merdeka No. 12", area: "Garut Kota", created_date: now() },
    { id: "p_mitra", user_id: "u_mitra", user_email: "mitra@demo.local", full_name: "Mitra SPPG Cikajang", role: "mitra", is_active: true, organization_name: "SPPG Cikajang", phone: "081234567891", address: "Jl. Raya Cikajang", created_date: now() },
    { id: "p_supplier", user_id: "u_supplier", user_email: "supplier@demo.local", full_name: "CV Binar Kalasenja", role: "supplier", is_active: true, organization_name: "CV Binar Kalasenja", phone: "081234567892", created_date: now() },
    { id: "p_logistik", user_id: "u_logistik", user_email: "logistik@demo.local", full_name: "Tim Logistik Pemkab Garut", role: "logistik", is_active: true, organization_name: "Dinas Ketahanan Pangan", phone: "081234567893", vehicle_type: "mobil_pickup", is_ready: true, created_date: now() },
    { id: "p_admin", user_id: "u_admin", user_email: "admin@demo.local", full_name: "Administrator", role: "admin", is_active: true, organization_name: "Dinas Ketahanan Pangan", phone: "081234567894", created_date: now() },
  ],
  Product: PRODUCTS.map((p, i) => ({
    id: p.id,
    name: p.name,
    category: p.category.toLowerCase(),
    price: p.price,
    base_price: p.old_price || p.price,
    unit: p.unit,
    stock: p.stock,
    origin: p.origin || "",
    image_url: p.img,
    supplier_name: "CV Binar Kalasenja",
    status: "active",
    created_date: daysAgo(i),
  })),
  WarehouseStock: [
    { id: uid("ws"), product_id: "kentang", product_name: "Kentang Granola", category: "sayuran", quantity: 120, unit: "kg", status: "active", updated_date: now(), created_date: daysAgo(2) },
    { id: uid("ws"), product_id: "beras", product_name: "Beras Premium Setra Ramos", category: "sembako", quantity: 320, unit: "kg", status: "active", updated_date: now(), created_date: daysAgo(2) },
    { id: uid("ws"), product_id: "telur", product_name: "Telur Ayam Negeri", category: "protein", quantity: 40, unit: "kg", status: "active", updated_date: now(), created_date: daysAgo(2) },
    { id: uid("ws"), product_id: "cabai-merah", product_name: "Cabai Merah Keriting", category: "bumbu", quantity: 12, unit: "kg", status: "low", updated_date: now(), created_date: daysAgo(2) },
  ],
  Order: [
    {
      id: uid("order"),
      order_number: "ORD-2026-0001",
      mitra_id: "mitra@demo.local",
      mitra_name: "Mitra SPPG Cikajang",
      supplier_name: "CV Binar Kalasenja",
      supplier_id: "supplier@demo.local",
      items: [
        { product_id: "kentang", product_name: "Kentang Granola", quantity: 20, unit: "kg", price: 14000 },
        { product_id: "beras", product_name: "Beras Premium Setra Ramos", quantity: 50, unit: "kg", price: 15500 },
      ],
      total: 1055000,
      delivery_fee: 12000,
      payment_method: "Transfer Bank",
      status: "delivered",
      tracking: [
        { status: "Menunggu Konfirmasi", at: daysAgo(3), note: "Pesanan dibuat" },
        { status: "Diproses", at: daysAgo(2), note: "Supplier menyiapkan barang" },
        { status: "Dikirim", at: daysAgo(1), note: "Barang dalam perjalanan" },
        { status: "Selesai", at: daysAgo(0), note: "Pesanan diterima" },
      ],
      driver: "Pak Rudi",
      created_date: daysAgo(3),
    },
    {
      id: uid("order"),
      order_number: "ORD-2026-0002",
      mitra_id: "mitra@demo.local",
      mitra_name: "Mitra SPPG Cikajang",
      supplier_name: "PT Berkah Jaya Supplier",
      supplier_id: "supplier@demo.local",
      items: [
        { product_id: "ayam", product_name: "Ayam Potong", quantity: 30, unit: "kg", price: 35000 },
        { product_id: "tomat", product_name: "Tomat Merah", quantity: 15, unit: "kg", price: 10000 },
      ],
      total: 1200000,
      delivery_fee: 12000,
      payment_method: "QRIS",
      status: "shipping",
      tracking: [
        { status: "Menunggu Konfirmasi", at: daysAgo(2), note: "Pesanan dibuat" },
        { status: "Diproses", at: daysAgo(1), note: "Supplier menyiapkan barang" },
        { status: "Dikirim", at: daysAgo(0), note: "Barang dalam perjalanan" },
      ],
      driver: "Pak Joko",
      created_date: daysAgo(2),
    },
    {
      id: uid("order"),
      order_number: "ORD-2026-0003",
      mitra_id: "mitra@demo.local",
      mitra_name: "Mitra SPPG Cikajang",
      supplier_name: "UD Shafira Jaya Abadi",
      supplier_id: "supplier@demo.local",
      items: [
        { product_id: "daging-sapi", product_name: "Daging Sapi Segar", quantity: 10, unit: "kg", price: 135000 },
      ],
      total: 1350000,
      delivery_fee: 12000,
      payment_method: "COD",
      status: "pending",
      tracking: [
        { status: "Menunggu Konfirmasi", at: daysAgo(0), note: "Pesanan dibuat" },
      ],
      driver: "",
      created_date: daysAgo(0),
    },
  ],
  PurchaseOrder: [
    { id: uid("po"), po_number: "PO-2026-0001", mitra_email: "mitra@demo.local", mitra_name: "Mitra SPPG Cikajang", supplier_email: "supplier@demo.local", supplier_name: "CV Binar Kalasenja", items: [{ product_id: "kentang", product_name: "Kentang Granola", quantity: 20, unit: "kg" }], total: 280000, status: "diproses", has_supplier: true, created_date: daysAgo(1) },
    { id: uid("po"), po_number: "PO-2026-0002", mitra_email: "mitra@demo.local", mitra_name: "Mitra SPPG Cikajang", supplier_email: "supplier@demo.local", supplier_name: "PT Berkah Jaya Supplier", items: [{ product_id: "ayam", product_name: "Ayam Potong", quantity: 30, unit: "kg" }], total: 1050000, status: "menunggu", has_supplier: true, created_date: daysAgo(1) },
  ],
  Transaction: [
    {
      id: uid("tx"),
      user_email: "mitra@demo.local",
      mitra_id: "mitra@demo.local",
      transaction_number: "TRX-20260801-0001",
      payment_status: "paid",
      delivery_status: "delivered",
      payment_method: "Transfer Bank",
      items: [
        { product_id: "kentang", product_name: "Kentang Granola", supplier_name: "CV Binar Kalasenja", quantity: 20, unit: "kg", subtotal: 280000 },
        { product_id: "telur", product_name: "Telur Ayam Negeri", supplier_name: "CV Binar Kalasenja", quantity: 10, unit: "kg", subtotal: 270000 },
      ],
      subtotal: 550000,
      service_fee: 16500,
      delivery_fee: 15000,
      total: 581500,
      delivery_address: "Jl. Raya Cikajang, Garut",
      amount: 1055000,
      method: "Transfer Bank",
      status: "success",
      created_date: daysAgo(3),
    },
    {
      id: uid("tx"),
      user_email: "mitra@demo.local",
      mitra_id: "mitra@demo.local",
      transaction_number: "TRX-20260802-0002",
      payment_status: "paid",
      delivery_status: "shipping",
      payment_method: "QRIS",
      items: [
        { product_id: "ayam", product_name: "Ayam Potong", supplier_name: "CV Binar Kalasenja", quantity: 30, unit: "kg", subtotal: 1050000 },
        { product_id: "beras", product_name: "Beras Premium Setra Ramos", supplier_name: "CV Binar Kalasenja", quantity: 10, unit: "kg", subtotal: 155000 },
      ],
      subtotal: 1205000,
      service_fee: 36150,
      delivery_fee: 15000,
      total: 1256150,
      delivery_address: "Jl. Raya Cikajang, Garut",
      amount: 1200000,
      method: "QRIS",
      status: "success",
      created_date: daysAgo(2),
    },
    {
      id: uid("tx"),
      user_email: "adhiramaharani@gmail.com",
      mitra_id: "adhiramaharani@gmail.com",
      transaction_number: "TRX-20260803-0003",
      payment_status: "paid",
      delivery_status: "delivered",
      payment_method: "COD",
      items: [
        { product_id: "bayam", product_name: "Bayam Hijau", supplier_name: "Toko Tani Garut", quantity: 2, unit: "ikat", subtotal: 10000 },
        { product_id: "telur", product_name: "Telur Ayam Negeri", supplier_name: "Toko Tani Garut", quantity: 1, unit: "kg", subtotal: 27000 },
      ],
      subtotal: 37000,
      service_fee: 1110,
      delivery_fee: 12000,
      total: 50110,
      delivery_address: "Jl. Merdeka No. 12, Garut Kota, Kabupaten Garut",
      amount: 41000,
      method: "COD",
      status: "success",
      created_date: daysAgo(1),
    },
  ],
  WeeklyMenu: [
    { id: uid("wm"), week_label: WEEKLY_MENU.week_label, status: "published", menu_data: WEEKLY_MENU.menu_data, created_date: now() },
  ],
  WeeklyNeeds: [
    { id: uid("wn"), sppg_id: "mitra@demo.local", sppg_name: "Mitra SPPG Cikajang", product_id: "kentang", product_name: "Kentang Granola", quantity: 100, unit: "kg", week_label: "Minggu Ini", status: "open", has_supplier: false, created_date: daysAgo(1) },
    { id: uid("wn"), sppg_id: "mitra@demo.local", sppg_name: "Mitra SPPG Cikajang", product_id: "telur", product_name: "Telur Ayam Negeri", quantity: 60, unit: "kg", week_label: "Minggu Ini", status: "open", has_supplier: false, created_date: daysAgo(1) },
  ],
  StockAlert: [
    { id: uid("sa"), product_id: "cabai-merah", product_name: "Cabai Merah Keriting", message: "Stok Cabai Merah Keriting menipis (12 kg)", level: "warning", status: "active", week_label: "Minggu Ini", created_date: daysAgo(0) },
    { id: uid("sa"), product_id: "telur", product_name: "Telur Ayam Negeri", message: "Stok Telur Ayam Negeri mulai rendah", level: "info", status: "active", week_label: "Minggu Ini", created_date: daysAgo(0) },
  ],
  Notification: [
    { id: uid("notif"), title: "Pesanan Baru Masuk", message: "Ada pesanan baru dari Mitra SPPG Cikajang", type: "order", read: false, created_date: daysAgo(0) },
    { id: uid("notif"), title: "Stok Menipis", message: "Stok Cabai Merah Keriting menipis", type: "stock", read: false, created_date: daysAgo(0) },
  ],
  ChatMessage: [
    { id: uid("chat"), channel: "admin-mitra", from: "mitra@demo.local", from_name: "Mitra SPPG Cikajang", text: "Selamat pagi, ada update ketersediaan beras?", created_date: daysAgo(1) },
    { id: uid("chat"), channel: "admin-supplier", from: "supplier@demo.local", from_name: "CV Binar Kalasenja", text: "Pengiriman beras sudah kami proses.", created_date: daysAgo(1) },
    { id: uid("chat"), channel: "admin-logistik", from: "logistik@demo.local", from_name: "Tim Logistik", text: "Armada siap berangkat ke Cikajang.", created_date: daysAgo(1) },
  ],
  SupplierRating: [
    { id: uid("sr"), sppg_id: "mitra@demo.local", supplier_name: "CV Binar Kalasenja", stars: 5, comment: "Pengiriman cepat dan barang berkualitas.", created_date: daysAgo(1) },
    { id: uid("sr"), sppg_id: "mitra@demo.local", supplier_name: "PT Berkah Jaya Supplier", stars: 4, comment: "Baik, tapi ada sedikit keterlambatan.", created_date: daysAgo(2) },
  ],
  DriverRating: [
    { id: uid("dr"), mitra_id: "mitra@demo.local", driver_name: "Pak Rudi", stars: 5, comment: "Tepat waktu dan ramah.", created_date: daysAgo(1) },
  ],
  ShoppingHistory: [
    { id: uid("sh"), user_email: "mitra@demo.local", items: [{ product_id: "kentang", product_name: "Kentang Granola", quantity: 20 }], total: 280000, created_date: daysAgo(3) },
  ],
  JobOpening: [
    {
      id: uid("job"),
      title: "Petugas Dapur — SPPG Cikajang",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "SPPG Cikajang, Garut",
      salary: "Rp 1.750.000 / bulan",
      quota: 5,
      status: "open",
      description: "Membantu penyiapan dan pengemasan makanan bergizi untuk para siswa sesuai standar menu MBG. Meliputi pencucian bahan, memasak, dan kebersihan dapur.",
      requirements: "Sehat & rajin • Siap bekerja pagi • Pengalaman dapur nilai plus",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Pengemudi / Kurir Logistik MBG",
      category: "logistik",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Kantor Dinas Ketahanan Pangan, Garut",
      salary: "Rp 2.200.000 / bulan",
      quota: 3,
      status: "open",
      description: "Mengantar bahan pangan dari warehouse ke SPPG dan dapur sekolah sesuai jadwal. Menjaga ketepatan waktu dan kelengkapan muatan.",
      requirements: "Memiliki SIM C minimum, menguasai rute Garut, bertanggung jawab",
      created_date: daysAgo(2),
    },
{
      id: uid("job"),
      title: "Helper Gudang / Warehouse",
      category: "lainnya",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "Warehouse Pusat, Garut Kota",
      salary: "Rp 1.600.000 / bulan",
      quota: 4,
      status: "open",
      description: "Membantu penataan stok, bongkar-muat, dan pengecekan kualitas bahan pangan yang masuk dan keluar gudang MBG.",
      requirements: "Jujur, teliti, mampu bekerja sama dalam tim",
      created_date: daysAgo(3),
    },
    {
      id: uid("job"),
      title: "Asisten Koki / Masak — SPPG Bayongbong",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "SPPG Bayongbong, Garut",
      salary: "Rp 1.850.000 / bulan",
      quota: 3,
      status: "open",
      description: "Membantu koki utama menyiapkan bahan, memasak, dan mengemas hidangan bergizi sesuai menu harian MBG.",
      requirements: "Pengalaman dapur minimal 1 tahun • Higienis • Jujur",
      created_date: daysAgo(0),
    },
    {
      id: uid("job"),
      title: "Pengampil / Packer Makanan",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "Dapur MBG Tarogong, Garut",
      salary: "Rp 1.500.000 / bulan",
      quota: 6,
      status: "open",
      description: "Menjalankan pengemasan makanan per porsi, pemeriksaan kebersihan wadah, dan kebersihan area pengemasan.",
      requirements: "Teliti dan higienis • Siap kerja pagi",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Petugas Penerimaan Bahan",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "SPPG Dapur MBG, Garut Kota",
      salary: "Rp 1.620.000 / bulan",
      quota: 2,
      status: "closed",
      description: "Menerima, menimbang, dan mencatat bahan pangan masuk dari supplier sesuai purchase order.",
      requirements: "Teliti • Mampu hitung dasar",
      created_date: daysAgo(4),
    },
    {
      id: uid("job"),
      title: "Koordinator Distribusi Logistik",
      category: "logistik",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Posko Distribusi, Garut Tengah",
      salary: "Rp 2.500.000 / bulan",
      quota: 1,
      status: "open",
      description: "Mengatur jadwal pengiriman, mengawasi armada, memastikan bahan sampai ke SPPG tepat waktu.",
      requirements: "Pengalaman koordinasi logistik • Menguasia jadwal & rute",
      created_date: daysAgo(0),
    },
    {
      id: uid("job"),
      title: "Doorman / Petugas Muat-Bongkar",
      category: "logistik",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Warehouse & SPPG se-Garut",
      salary: "Rp 1.550.000 / bulan",
      quota: 4,
      status: "open",
      description: "Membantu bongkar-muat bahan pangan, pengelolla rearrang area gudang, dan pengecad jumlah harian.",
      requirements: "Fisik kuat • Disiplin jadwal",
      created_date: daysAgo(3),
    },
    {
      id: uid("job"),
      title: "Pengecekan Mutu Bahan (QC)",
      category: "lainnya",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "QC Center, Garut Kota",
      salary: "Rp 1.900.000 / bulan",
      quota: 2,
      status: "open",
      description: "Memeriksa kualitas, kesegaran, dan berat bahan pangan sebelum wilayah dikirim ke dapur.",
      requirements: "Teliti • Siap kerja lapangan",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Staf Administrasi MBG",
      category: "lainnya",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "Kantor Dinas, Garut Kota",
      salary: "Rp 1.750.000 / bulan",
      quota: 2,
      status: "open",
      description: "Mengelola dokumen pencatatan, laporan harian penerimaan/pengeluaran, dan koordinasi data MBG.",
      requirements: "Menguasai Ms Office • Rapi & teliti",
      created_date: daysAgo(2),
    },
    {
      id: uid("job"),
      title: "Kepala Dapur SPPG — Garut Kota",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "SPPG Dapur MBG, Garut Kota",
      salary: "Rp 2.800.000 / bulan",
      quota: 1,
      status: "open",
      description: "Memimpin tim dapur, memastikan standar gizi dan kebersihan, mengatur jadwal masak, serta bertanggung jawab atas kualitas menu harian MBG.",
      requirements: "Pengalaman kepala dapur minimal 2 tahun • Kepemimpinan baik",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Pengelola Gizi SPPG",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "SPPG Cikajang, Garut",
      salary: "Rp 2.300.000 / bulan",
      quota: 2,
      status: "open",
      description: "Menyusun menu sesuai kebutuhan gizi siswa, menghitung takaran porsi, dan memastikan standar pemenuhan gizi MBG.",
      requirements: "Latar belakang gizi/kesehatan • Teliti & menyukai data",
      created_date: daysAgo(2),
    },
    {
      id: uid("job"),
      title: "Dispatcher / Petugas Penjadwalan",
      category: "logistik",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Posko Distribusi, Garut Tengah",
      salary: "Rp 2.100.000 / bulan",
      quota: 2,
      status: "open",
      description: "Menyusun dan memantau jadwal pengiriman harian, menghubungkan armada dengan SPPG tujuan, dan menangani penyesuaian rute.",
      requirements: "Jago koordinasi • Terbiasa dengan jadwal padat",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Supir Truk Distribusi",
      category: "logistik",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Gudang Distribusi, Garut",
      salary: "Rp 2.400.000 / bulan",
      quota: 4,
      status: "open",
      description: "Mengendarai truk distribusi bahan pangan ke SPPG se-Kabupaten Garut, menjaga kelengkapan dokumen pengiriman dan keamanan muatan.",
      requirements: "SIM B1 minimum • Pengalaman truk minimal 1 tahun",
      created_date: daysAgo(3),
    },
    {
      id: uid("job"),
      title: "Security Gudang MBG",
      category: "lainnya",
      owner_role: "logistik",
      owner_email: "logistik@demo.local",
      location: "Warehouse Pusat, Garut Kota",
      salary: "Rp 1.500.000 / bulan",
      quota: 2,
      status: "open",
      description: "Menjaga keamanan gudang, mengawasi arus keluar-masuk barang, dan melaporkan kondisi area secara berkala.",
      requirements: "Sehat & disiplin • Siap jadwal shift",
      created_date: daysAgo(1),
    },
    {
      id: uid("job"),
      title: "Tenaga Kebersihan Dapur",
      category: "sppg",
      owner_role: "mitra",
      owner_email: "mitra@demo.local",
      location: "Dapur MBG Tarogong, Garut",
      salary: "Rp 1.450.000 / bulan",
      quota: 5,
      status: "closed",
      description: "Membersihkan area dapur dan peralatan memasak, menjaga standar higienitas sesuai prosedur MBG.",
      requirements: "Rajin & higienis • Jujur",
      created_date: daysAgo(5),
    },
  ],
  Notification: [
    {
      id: uid("ntf"),
      type: "job_application",
      title: "Ada Pelamar Baru",
      message: "Siti Rahmawati melamar posisi \"Asisten Koki / Masak — SPPG Bayongbong\".",
      target_roles: ["mitra"],
      read_by: [],
      created_date: daysAgo(1),
    },
    {
      id: uid("ntf"),
      type: "job_application",
      title: "Ada Pelamar Baru",
      message: "Dedi Kurniawan melamar posisi \"Pengemudi / Kurir Logistik MBG\".",
      target_roles: ["logistik"],
      read_by: [],
      created_date: hoursAgo(3),
    },
    {
      id: uid("ntf"),
      type: "stock_alert",
      title: "Stok Beras Menipis",
      message: "Stok beras di bawah ambang batas. Segera lakukan penambahan.",
      target_roles: ["mitra", "admin"],
      read_by: [],
      created_date: hoursAgo(5),
    },
    {
      id: uid("ntf"),
      type: "new_order",
      title: "Pesanan Baru Masuk",
      message: "Mitra SPPG Cikajang mengirimkan pesanan bahan pangan baru.",
      target_roles: ["supplier"],
      read_by: [],
      created_date: hoursAgo(2),
    },
    {
      id: uid("ntf"),
      type: "order_update",
      title: "Pengiriman Sedang Berjalan",
      message: "Ada pengiriman yang sedang menuju SPPG tujuan. Pantau di menu pengiriman.",
      target_roles: ["logistik"],
      read_by: [],
      created_date: hoursAgo(1),
    },
    {
      id: uid("ntf"),
      type: "complaint",
      title: "Pengaduan Baru",
      message: "Warga melaporkan keterlambatan pengiriman di wilayah Tarogong.",
      target_roles: ["admin", "mitra"],
      read_by: [],
      created_date: hoursAgo(6),
    },
  ],
};

export function ensureSeed() {
  if (typeof window === "undefined") return;
  try {
    if (localStorage.getItem(SEED_VERSION)) return;
    Object.entries(COLLECTIONS).forEach(([name, items]) => {
      localStorage.setItem(`smb_collection_${name}`, JSON.stringify(items));
    });
    localStorage.setItem(SEED_VERSION, "1");
  } catch (e) {
    console.error("Gagal seed data lokal:", e);
  }
}

export function resetSeed() {
  if (typeof window === "undefined") return;
  Object.keys(COLLECTIONS).forEach((name) => {
    localStorage.removeItem(`smb_collection_${name}`);
  });
  localStorage.removeItem(SEED_VERSION);
  localStorage.removeItem("smb_session_user");
  localStorage.removeItem("smart_mbg_user");
  ensureSeed();
}
